# Generated by Django 5.1.3 on 2024-12-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
