# Generated by Django 5.1.2 on 2024-10-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auctions",
            "0004_auctionlisting_created_at_auctionlisting_current_bid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="current_bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
