# Generated by Django 5.1.2 on 2024-10-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_auctionlisting_current_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlisting",
            name="image_url",
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
