# Generated by Django 5.1 on 2024-11-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_auctionlisting_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="image",
            field=models.ImageField(upload_to="listings/"),
        ),
    ]
