# Generated by Django 5.1.3 on 2024-11-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user/default_profile.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
